language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

matrix:
  allow_failures:
    - python: "3.9-dev"

# command to install dependencies
install:
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run tests"

# command to run tests
# jobs:
  # include:
    # - stage: "✨ Flake8 Nit–Picking ✨"
      # python: "3.6"
      # script: "pipenv run flake8"
